import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext(null);
const STORAGE_KEY = 'nandi-language';

export const LANGUAGES = {
  en: 'English',
  hi: 'हिन्दी',
  kn: 'ಕನ್ನಡ',
};

const TRANSLATIONS = {
  en: {
    language: 'Language',
    dark: 'Dark',
    light: 'Light',
    addAnimal: 'Add animal',
    newHerdRecord: 'New herd record',
    animalType: 'Animal type',
    name: 'Name',
    animalId: 'Animal ID',
    breed: 'Breed',
    age: 'Age (years)',
    ownerId: 'Owner ID',
    cancel: 'Cancel',
    addToHerd: 'Add to herd',
    duplicateId: 'That animal ID is already in use. Choose another one.',
    highRiskBoard: 'High Risk Board',
    animalsFlagged: 'animals flagged',
    animal: 'Animal',
    species: 'Species',
    risk: 'Risk',
    score: 'Score',
    rumination: 'Rumination Δ',
    view: 'View',
    login: 'Log in',
    signup: 'Sign up',
    phone: 'Phone number',
    uniqueId: 'Unique ID',
    identifier: 'Sign in with',
    identifierPlaceholder: 'Enter your phone number',
    uniqueIdPlaceholder: 'Enter your unique ID',
    password: 'Password',
    fullName: 'Full name',
    signIn: 'Sign in to NANDI',
    createAccount: 'Create NANDI account',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
    logIn: 'Log in',
    signUp: 'Sign up',
    enterPlatform: 'Enter Platform',
    mainPage: 'Main Page',
    herdOverview: 'Herd Overview',
    analytics: 'Analytics',
    predictions: 'Predictions',
    history: 'History',
    animals: 'Animals',
    signupWith: 'Sign up with',
    backHome: 'Back to home',
    earlyCare: 'NANDI · Early care intelligence',
    authIntro: 'Sign in or create your workspace to keep every herd signal in view.',
    allSet: 'You are all set.',
    workspaceReceived: 'Workspace request received.',
    prototypeReady: 'Continue into the platform to explore the herd view.',
    welcomeBack: 'Welcome back',
    createWorkspace: 'Create your workspace',
    yourName: 'Your name',
    passwordPlaceholder: 'At least 8 characters',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    terms: 'By continuing, you agree to the NANDI workspace terms and privacy policy.',
    welcomeBackBang: 'Welcome back!',
    helloPartner: 'Hello, partner!',
    loginDescription: 'To keep your herd connected, sign in with your personal details.',
    signupDescription: 'Enter your details and start your connected herd journey with us.',
    herdTrends: 'Herd-wide trends across all connected devices.',
    riskDistribution: 'Risk distribution',
    averageRisk: 'Average risk by species',
    thi: 'Shed Temperature-Humidity Index (THI)',
    historyDescription: 'A chronological log of herd events and alerts.',
    predictionTitle: 'Predictions & Recommendations',
    predictionDescription: 'Explainable, animal-specific actions generated from the fused risk vector.',
    viewRecord: 'View full animal record →',
    noRecommendations: 'No active recommendations — herd is clear.',
    speciesLabel: 'Species',
    ageLabel: 'Age',
    lactation: 'Lactation',
    riskScore: 'Risk score',
    noAnimals: 'No animals recorded for this species yet.',
    cooperative: 'Kolar Village / milk cooperative',
    healthConsole: 'Herd Health Console',
    gatewayOnline: 'Gateway online · 99.4% uptime',
    fieldSignal: 'Field signal / 24-7',
    knowSooner: 'Know sooner.',
    careBetter: 'Care better.',
    heroDescription: 'NANDI turns the quietest changes in behaviour and milk chemistry into a clear care window for every animal.',
    exploreSystem: 'Explore the system',
    watchDemo: 'Watch demo on YouTube',
    signalWatch: 'Signal watch',
    live: 'LIVE',
    behaviourConfidence: 'Behaviour confidence · herd average',
    earlyCareWindow: 'Early care window',
    beforeSymptoms: 'before symptoms surface',
    connectedView: 'One connected view',
    wholeHerd: 'for the whole herd',
    todayInHerd: 'Today in the herd',
    earlierSignal: 'A clearer day starts with an earlier signal.',
    liveReadings: 'Live readings from every connected animal, distilled into the care decisions that matter now.',
    herdSize: 'Herd size',
    acrossSpecies: 'across 3 species',
    needsVet: 'needs vet attention',
    averageRiskScore: 'Average risk score',
    herdWide: 'herd-wide',
    gatewayUptime: 'Gateway uptime',
    last30Days: 'last 30 days',
    liveHerdReview: 'Live Herd Review',
    updatedMoments: 'Updated moments ago',
    noRiskAnimals: 'No moderate or high risk animals right now.',
    enterAnimalProfile: 'Enter the profile details to place this animal in your live herd view.',
    rfidTagLabel: 'RFID / AIN tag (8-15 alphanumeric characters)',
    rfidTagHelp: 'This is what the ESP32-S3 reader will scan off the RFID tag.',
    lactationNumberLabel: 'Lactation #',
    saving: 'Saving…',
    cowLabel: 'Cow',
    buffaloLabel: 'Buffalo',
    shedThiShort: 'Shed THI',
    runPredictionNow: 'Run prediction now',
    running: 'Running…',
    quarterLevelReadings: 'Quarter-level readings',
    noQuarterReadings: 'No quarter-level readings yet — waiting on the first Smart Cup telemetry for this animal.',
    recommendedAction: 'Recommended action',
    findNearbyVet: 'Find nearby vet',
    riskTrend30: '30-day risk trend',
    noRiskHistory: 'No risk history yet for this animal.',
    historyTitle: 'History',
    analyticsTitle: 'Analytics',
    liveAlertLabel: 'Live alert',
    dismissAlert: 'Dismiss alert',
    roleLabel: 'Role',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    pleaseWait: 'Please wait…',
    demoAccountsNote: 'Demo accounts (seeded): farmer@nandi.test · vet@nandi.test · harshkumar56367@gmail.com — password: Password123!',
    signInIdentifierLabel: 'Email, phone or Owner ID',
    signInIdentifierPlaceholder: 'you@example.com / phone / Owner ID',
    acceptTerms: 'I accept the terms and conditions.',
    phoneLabel: 'Mobile number',
    phoneRequiredNote: 'Required — used for urgent WhatsApp/SMS mastitis alerts.',
    farmNameLabel: 'Farm / Cooperative name (optional)',
    farmNamePlaceholder: 'e.g. Patel Dairy Farm',
    farmIdIssued: 'Your Farm ID',
    farmIdExplain: 'Enter this Farm ID into every Central Hub, collar and cup you set up, so their data always saves to your herd only.',
    copyFarmId: 'Copy',
    copiedFarmId: 'Copied!',
    logOut: 'Log out',
    herdAvgTrend30: 'Herd average risk score (30 days)',
    noHerdTrend: 'No risk history yet — trend appears once telemetry starts flowing in.',
    loadingHerd: 'Loading your herd from the backend…',
    checkingSession: 'Checking your session…',
    optional: 'optional',
    alertLanguage: 'Alert language',
    alertLanguageHelp: 'Twilio alerts will use this language.',
    removeAnimal: 'Remove animal',
    dateAxis: 'Date',
    speciesAxis: 'Species',
    riskAxis: 'Risk score (%)',
    weeklyCheckIn: 'Weekly check-in',
    weeklyInputTitle: 'Weekly herd check-in',
    weeklyInputDescription: 'Record numeric or choice-based farm inputs once each week.',
    weekStarting: 'Week starting',
    morningMilking: 'Morning milkings',
    eveningMilking: 'Evening milkings',
    feedKg: 'Feed per day (kg)',
    workerHygiene: 'Worker hygiene',
    good: 'Good',
    needsAttention: 'Needs attention',
    poor: 'Poor',
    antidoteGiven: 'Any cow given antidote?',
    antidoteAnimal: 'Antidote animal ID',
    selectAnimal: 'Select animal',
    yes: 'Yes',
    no: 'No',
    saveWeeklyInput: 'Save weekly input',
    weeklySaved: 'Weekly check-in saved.',
    downloadApk: 'Download Android app',
    disclaimer: 'Disclaimer',
    contact: 'Contact',
    apkUnavailable: 'Android package',
    footerAbout: 'Built for Smart India Hackathon 2026, Problem Statement 26109, issued by the Ministry of Fisheries, Animal Husbandry & Dairying.',
    footerDisclaimer: 'NANDI is a hackathon prototype and decision-support aid, not a certified veterinary diagnostic device. Risk scores and recommendations do not replace examination by a qualified veterinarian.',
    exploreSignal: 'Explore the signal', smartCollar: 'Smart Collar', smartCollarDescription: 'Worn continuously, it watches behaviour, rumination and motility for the earliest signal of systemic distress.', smartCup: 'Digi-Cup', smartCupDescription: "At milking time, it reads each quarter's chemistry and rheology directly in under 45 seconds per cow.", nandiHub: 'Central Hub', nandiHubDescription: 'The always-on gateway collects every collar and cup signal, buffers it locally and keeps the cloud timeline alive.', threeSignals: 'Three signals. One calmer day.', threeSignalsDescription: 'Every signal has a place: on the animal, at milking time and at the gateway.', nandiDevices: 'NANDI devices', alwaysOnSensing: 'Always-on sensing', milkingIntelligence: 'Milking intelligence', farmWideRelay: 'Farm-wide relay', workflowTitle: 'From teat to alert, in six steps',
    vetRequests: 'Vet Requests',

    regionalAnalysis: 'Regional Analysis',
    selectFarmOwner: 'Select farm owner',
    animalName: 'Animal name',
    displayTag: 'Display tag',
    charRfid: '8-15 character RFID',
    remove: 'Remove',
    farmLabel: 'Farm',
    permanentAction: 'Permanent action',
    removeAnimalConfirm: 'Remove animal',
    removeAccountConfirm: 'Remove account',
    addAccountOrFarm: 'Add account or farm',
    refresh: 'Refresh',
    hubMonitoringByState: 'Hub monitoring by state',
    regionalRiskMap: 'Regional risk map',
    stateLabel: 'State',
    noStatesAvailable: 'No states available',


    mpu6050: 'MPU6050',
    motility: 'Motility',
    loraRadio: 'LoRa radio',
    loraRange: '3–5 km range',
    solarCell: 'Solar cell',
    solarReserve: '195-day reserve',
    ecPh: 'EC + pH',
    chemistry: 'Chemistry',
    irProbe: 'IR probe',
    temperature: 'Temperature',
    rfid: 'RFID',
    lora: 'LoRa',
    signalBridge: 'Signal bridge',
    wifi4g: 'Wi-Fi + 4G',
    cloudSync: 'Cloud sync',
    devicesConnected: '250+',
    devicesConnectedCount: 'Devices connected',
    collarFlow1: 'Sense motion + temperature',
    collarFlow2: 'Compress a live behaviour signal',
    collarFlow3: 'Broadcast over LoRa',
    cupFlow1: 'Identify the animal by RFID',
    cupFlow2: 'Sample all four quarters',
    cupFlow3: 'Return chemistry + rheology',
    hubFlow1: 'Collect collar and cup packets',
    hubFlow2: 'Buffer readings at the edge',
    hubFlow3: 'Sync one herd timeline',
    mcuName: 'ESP-WROOM-32',
    mcuRole: 'Core controller',
    collarMcuDetail: 'Deep-sleep scheduling, reads sensors, formats LoRa packets.',
    imuName: 'MPU6050',
    imuRole: 'Motility & rumination',
    imuDetail: 'Accelerometer + gyroscope catches jaw rhythm and head motion; a rumination drop >15% signals distress.',
    tempName: 'DS18B20',
    tempRole: 'Skin temperature',
    tempDetail: 'Waterproof probe against the neck tracks basal temperature and pre-clinical fever.',
    radioName: 'SX1278 LoRa',
    radioRole: 'Long-range radio',
    radioDetail: 'Sends telemetry 3–5 km to the gateway with no SIM card or Wi-Fi needed.',
    solarName: 'Solar + 18650 cell',
    solarRole: 'Power',
    collarSolarDetail: '1W panel trickle-charges the battery for a ~195-day dark reserve.',
    cupMcuDetail: 'Runs sequential 4-quarter sampling and drives the OLED UI.',
    ecPhName: 'EC + pH probes',
    ecPhRole: 'Milk chemistry',
    ecPhDetail: 'Detects the ionic conductivity rise and alkaline shift (pH > 6.8) of leaking mammary tissue.',
    cmtName: 'Motor + INA219',
    cmtRole: 'Viscosity (CMT)',
    cmtDetail: 'A geared paddle strains against thickened gel; current draw quantifies somatic cell count.',
    irName: 'MLX90614',
    irRole: 'IR teat temperature',
    irDetail: 'Flags localised quarter inflammation from surface heat alone.',
    rfidName: '134.2 kHz LF RFID',
    rfidRole: 'Animal ID',
    rfidDetail: 'Reads the RFID tag through milk and mud in under a second.',
    gatewayName: 'LoRa gateway',
    gatewayRole: 'Signal collection',
    gatewayDetail: 'Receives encrypted telemetry from collars and cups across the shed and field edge.',
    backhaulName: 'Wi-Fi + 4G backhaul',
    backhaulRole: 'Cloud sync',
    backhaulDetail: 'Keeps the herd timeline current even when the farm network changes state.',
    storageName: 'Edge buffer',
    storageRole: 'Offline resilience',
    storageDetail: 'Stores readings locally and forwards them when connectivity returns.',
    hubPowerName: 'Battery backup',
    hubPowerRole: 'Always-on uptime',
    hubPowerDetail: 'Maintains the signal bridge through short power interruptions.',
    hubSolarName: 'Solar powered charging',
    hubSolarRole: 'Renewable power',
    hubSolarDetail: 'Uses sunlight to keep the Central Hub charged and ready for continuous operation.',
    step1Title: 'Scan the Collar RFID tag',
    step1Detail: 'The cup’s RFID reader pulls the animal ID and lactation history in under 500ms.',
    step2Title: 'Sample each quarter',
    step2Detail: 'EC, pH and IR temperature are read per-quarter, ~10 seconds each.',
    step3Title: 'Run the CMT check',
    step3Detail: 'A motorised paddle spin measures reagent viscosity — an uncheatable proxy for SCC.',
    step4Title: 'Broadcast over LoRa',
    step4Detail: 'Cup and collar both send encrypted packets to the shed gateway.',
    step5Title: 'Fuse & forecast',
    step5Detail: 'Cloud AI combines chemistry, rumination and weather into a 7–14 day risk score.',
    step6Title: 'Send alerts',
    step6Detail: 'Alerts are sent to farmers and vets so the right care can begin sooner.',
    adminConsole: 'Administrators Console',
    vetConsole: 'Veterinary Officer Console',
    totalFarms: 'TOTAL FARMS',
    totalAnimals: 'TOTAL ANIMALS',
    registeredAccounts: 'REGISTERED ACCOUNTS',
    highRiskAnimals: 'HIGH-RISK ANIMALS',
    accountOverview: 'Account overview',
    mainAdministrator: 'Main Administrator',

  },
  hi: {
    language: 'भाषा',
    dark: 'डार्क',
    light: 'लाइट',
    addAnimal: 'पशु जोड़ें',
    newHerdRecord: 'नया झुंड रिकॉर्ड',
    animalType: 'पशु का प्रकार',
    name: 'नाम',
    animalId: 'पशु आईडी',
    breed: 'नस्ल',
    age: 'आयु (वर्ष)',
    ownerId: 'मालिक आईडी',
    cancel: 'रद्द करें',
    addToHerd: 'झुंड में जोड़ें',
    duplicateId: 'यह पशु आईडी पहले से उपयोग में है। दूसरी आईडी चुनें।',
    highRiskBoard: 'उच्च जोखिम बोर्ड',
    animalsFlagged: 'पशु चिह्नित',
    animal: 'पशु',
    species: 'प्रजाति',
    risk: 'जोखिम',
    score: 'स्कोर',
    rumination: 'जुगाली Δ',
    view: 'देखें',
    login: 'लॉग इन',
    signup: 'साइन अप',
    phone: 'फ़ोन नंबर',
    uniqueId: 'यूनिक आईडी',
    identifier: 'इसके साथ साइन इन करें',
    identifierPlaceholder: 'अपना फ़ोन नंबर दर्ज करें',
    uniqueIdPlaceholder: 'अपनी यूनिक आईडी दर्ज करें',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    signIn: 'NANDI में साइन इन करें',
    createAccount: 'NANDI अकाउंट बनाएं',
    switchToLight: 'लाइट मोड पर जाएं',
    switchToDark: 'डार्क मोड पर जाएं',
    logIn: 'लॉग इन',
    signUp: 'साइन अप',
    enterPlatform: 'प्लेटफ़ॉर्म खोलें',
    mainPage: 'मुख्य पृष्ठ',
    herdOverview: 'झुंड का अवलोकन',
    analytics: 'विश्लेषण',
    predictions: 'पूर्वानुमान',
    history: 'इतिहास',
    animals: 'पशु',
    signupWith: 'इसके साथ साइन अप करें',
    backHome: 'होम पर वापस जाएं',
    earlyCare: 'NANDI · शुरुआती देखभाल बुद्धिमत्ता',
    authIntro: 'हर झुंड संकेत पर नज़र रखने के लिए साइन इन करें या अपना कार्यक्षेत्र बनाएं।',
    allSet: 'आप तैयार हैं।',
    workspaceReceived: 'कार्यस्थल अनुरोध प्राप्त हुआ।',
    prototypeReady: 'यह प्रोटोटाइप अगले चरण के लिए तैयार है। झुंड दृश्य देखने के लिए प्लेटफ़ॉर्म पर जाएं।',
    welcomeBack: 'वापसी पर स्वागत है',
    createWorkspace: 'अपना कार्यक्षेत्र बनाएं',
    yourName: 'आपका नाम',
    passwordPlaceholder: 'कम से कम 8 अक्षर',
    hidePassword: 'पासवर्ड छिपाएं',
    showPassword: 'पासवर्ड दिखाएं',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    terms: 'जारी रखकर, आप NANDI कार्यक्षेत्र की शर्तों और गोपनीयता नीति से सहमत हैं।',
    welcomeBackBang: 'वापसी पर स्वागत है!',
    helloPartner: 'नमस्ते साथी!',
    loginDescription: 'अपने झुंड को जुड़ा रखने के लिए अपनी जानकारी से साइन इन करें।',
    signupDescription: 'अपनी जानकारी दर्ज करें और अपने जुड़े झुंड की यात्रा शुरू करें।',
    herdTrends: 'सभी जुड़े उपकरणों के झुंड-व्यापी रुझान।',
    riskDistribution: 'जोखिम वितरण',
    averageRisk: 'प्रजाति के अनुसार औसत जोखिम',
    thi: 'शेड तापमान-आर्द्रता सूचकांक (THI)',
    historyDescription: 'झुंड की घटनाओं और अलर्ट का कालानुक्रमिक लॉग।',
    predictionTitle: 'पूर्वानुमान और सुझाव',
    predictionDescription: 'संयुक्त जोखिम संकेत से बनाए गए समझाने योग्य, पशु-विशिष्ट सुझाव।',
    viewRecord: 'पूरा पशु रिकॉर्ड देखें →',
    noRecommendations: 'कोई सक्रिय सुझाव नहीं — झुंड सुरक्षित है।',
    speciesLabel: 'प्रजाति',
    ageLabel: 'आयु',
    lactation: 'दुग्धावस्था',
    riskScore: 'जोखिम स्कोर',
    noAnimals: 'इस प्रजाति के लिए अभी कोई पशु दर्ज नहीं है।',
    cooperative: 'कोलार गांव / दुग्ध सहकारी',
    healthConsole: 'झुंड स्वास्थ्य कंसोल',
    gatewayOnline: 'गेटवे ऑनलाइन · 99.4% अपटाइम',
    fieldSignal: 'फील्ड संकेत / 24-7',
    knowSooner: 'जल्दी जानें।',
    careBetter: 'बेहतर देखभाल करें।',
    heroDescription: 'NANDI व्यवहार और दूध की रसायन में होने वाले सूक्ष्म बदलावों को हर पशु के लिए स्पष्ट देखभाल अवसर में बदलता है।',
    exploreSystem: 'सिस्टम देखें',
    watchDemo: 'YouTube पर डेमो देखें',
    signalWatch: 'संकेत निगरानी',
    live: 'लाइव',
    behaviourConfidence: 'व्यवहार विश्वास · झुंड औसत',
    earlyCareWindow: 'शुरुआती देखभाल अवसर',
    beforeSymptoms: 'लक्षण दिखने से पहले',
    connectedView: 'एक जुड़ा दृश्य',
    wholeHerd: 'पूरे झुंड के लिए',
    todayInHerd: 'आज झुंड में',
    earlierSignal: 'एक स्पष्ट दिन पहले संकेत से शुरू होता है।',
    liveReadings: 'हर जुड़े पशु की लाइव रीडिंग को अभी महत्वपूर्ण देखभाल निर्णयों में बदला गया है।',
    herdSize: 'झुंड का आकार',
    acrossSpecies: '3 प्रजातियों में',
    needsVet: 'पशु चिकित्सक की जरूरत',
    averageRiskScore: 'औसत जोखिम स्कोर',
    herdWide: 'पूरे झुंड का',
    gatewayUptime: 'गेटवे अपटाइम',
    last30Days: 'पिछले 30 दिन',
    liveHerdReview: 'लाइव झुंड समीक्षा',
    updatedMoments: 'अभी अपडेट किया गया',
    noRiskAnimals: 'अभी कोई मध्यम या उच्च जोखिम वाला पशु नहीं है।',
    enterAnimalProfile: 'इस पशु को अपने झुंड में जोड़ने के लिए प्रोफ़ाइल विवरण भरें।',
    rfidTagLabel: 'RFID / AIN टैग (8-15 अक्षर और अंक)',
    rfidTagHelp: 'ESP32-S3 रीडर कान के टैग से यही स्कैन करेगा।',
    lactationNumberLabel: 'स्तनपान संख्या',
    saving: 'सहेजा जा रहा है…',
    cowLabel: 'गाय',
    buffaloLabel: 'भैंस',
    shedThiShort: 'शेड THI',
    runPredictionNow: 'अभी पूर्वानुमान चलाएं',
    running: 'चल रहा है…',
    quarterLevelReadings: 'क्वार्टर-स्तर की रीडिंग',
    noQuarterReadings: 'अभी तक कोई क्वार्टर-स्तर की रीडिंग नहीं — इस पशु के लिए पहली स्मार्ट कप टेलीमेट्री की प्रतीक्षा है।',
    recommendedAction: 'सुझाई गई कार्रवाई',
    findNearbyVet: 'नज़दीकी पशु चिकित्सक खोजें',
    riskTrend30: '30-दिन का जोखिम रुझान',
    noRiskHistory: 'इस पशु के लिए अभी तक कोई जोखिम इतिहास नहीं है।',
    historyTitle: 'इतिहास',
    analyticsTitle: 'विश्लेषण',
    liveAlertLabel: 'लाइव अलर्ट',
    dismissAlert: 'अलर्ट हटाएं',
    roleLabel: 'भूमिका',
    emailLabel: 'ईमेल',
    emailPlaceholder: 'you@example.com',
    pleaseWait: 'कृपया प्रतीक्षा करें…',
    demoAccountsNote: 'डेमो खाते: farmer@nandi.test · vet@nandi.test · admin@nandi.test — पासवर्ड: Password123!',
    signInIdentifierLabel: 'ईमेल, फ़ोन या फार्म आईडी',
    signInIdentifierPlaceholder: 'ईमेल / फ़ोन / फार्म आईडी दर्ज करें',
    phoneLabel: 'मोबाइल नंबर',
    phoneRequiredNote: 'आवश्यक — तत्काल WhatsApp/SMS मस्टाइटिस अलर्ट के लिए उपयोग होता है।',
    farmNameLabel: 'फार्म / सहकारी समिति का नाम (वैकल्पिक)',
    farmNamePlaceholder: 'उदा. पटेल डेयरी फार्म',
    farmIdIssued: 'आपकी फार्म आईडी',
    farmIdExplain: 'इस फार्म आईडी को अपने हर हब, कॉलर और कप में दर्ज करें, ताकि डेटा हमेशा केवल आपके झुंड में सहेजा जाए।',
    copyFarmId: 'कॉपी करें',
    copiedFarmId: 'कॉपी हो गया!',
    logOut: 'लॉग आउट',
    herdAvgTrend30: 'झुंड का औसत जोखिम स्कोर (30 दिन)',
    noHerdTrend: 'अभी तक कोई जोखिम इतिहास नहीं — टेलीमेट्री शुरू होते ही रुझान दिखाई देगा।',
    loadingHerd: 'आपका झुंड बैकएंड से लोड हो रहा है…',
    checkingSession: 'आपका सत्र जांचा जा रहा है…',
    exploreSignal: 'संकेत देखें', smartCollar: 'स्मार्ट कॉलर', smartCollarDescription: 'यह व्यवहार, जुगाली और गति पर लगातार नज़र रखता है।', smartCup: 'डिजी-कप', smartCupDescription: 'दूध निकालते समय यह 45 सेकंड से कम में हर क्वार्टर की जांच करता है।', nandiHub: 'सेंट्रल हब', nandiHubDescription: 'हमेशा चालू गेटवे सभी कॉलर और कप संकेतों को एकत्र करता है।', threeSignals: 'तीन संकेत। एक शांत दिन।', threeSignalsDescription: 'हर संकेत का अपना स्थान है: पशु पर, दुहने के समय और गेटवे पर।', nandiDevices: 'NANDI उपकरण', alwaysOnSensing: 'हमेशा चालू सेंसर', milkingIntelligence: 'दुहाई बुद्धिमत्ता', farmWideRelay: 'पूरे फार्म का रिले', workflowTitle: 'थन से अलर्ट तक, छह चरणों में',
    optional: 'वैकल्पिक', alertLanguage: 'अलर्ट की भाषा', alertLanguageHelp: 'Twilio अलर्ट इसी भाषा में आएंगे।', removeAnimal: 'पशु हटाएं', dateAxis: 'तारीख', speciesAxis: 'प्रजाति', riskAxis: 'जोखिम स्कोर (%)', weeklyCheckIn: 'साप्ताहिक जांच', weeklyInputTitle: 'साप्ताहिक झुंड जांच', weeklyInputDescription: 'हर सप्ताह संख्यात्मक या विकल्प-आधारित जानकारी दर्ज करें।', weekStarting: 'सप्ताह शुरू', morningMilking: 'सुबह दुहना', eveningMilking: 'शाम दुहना', feedKg: 'प्रतिदिन चारा (किग्रा)', workerHygiene: 'कर्मचारी स्वच्छता', good: 'अच्छी', needsAttention: 'ध्यान चाहिए', poor: 'खराब', antidoteGiven: 'क्या किसी गाय को एंटीडोट दिया?', antidoteAnimal: 'एंटीडोट पशु आईडी', selectAnimal: 'पशु चुनें', yes: 'हां', no: 'नहीं', saveWeeklyInput: 'साप्ताहिक जानकारी सहेजें', weeklySaved: 'साप्ताहिक जांच सहेजी गई।', downloadApk: 'Android ऐप डाउनलोड करें', disclaimer: 'अस्वीकरण', contact: 'संपर्क', apkUnavailable: 'Android पैकेज', footerAbout: 'स्मार्ट इंडिया हैकाथॉन 2026, समस्या विवरण 26109 के लिए बनाया गया।', footerDisclaimer: 'NANDI एक हैकाथॉन प्रोटोटाइप और निर्णय-सहायता उपकरण है, प्रमाणित पशु चिकित्सा निदान उपकरण नहीं।',

    mpu6050: 'एमपीयू6050 (MPU6050)',
    motility: 'गतिशीलता',
    loraRadio: 'लोरा (LoRa) रेडियो',
    loraRange: '3-5 किमी रेंज',
    solarCell: 'सौर सेल',
    solarReserve: '195-दिन का रिज़र्व',
    ecPh: 'ईसी + पीएच (EC + pH)',
    chemistry: 'रसायन',
    irProbe: 'आईआर (IR) जांच',
    temperature: 'तापमान',
    rfid: 'आरएफआईडी (RFID)',
    lora: 'लोरा (LoRa)',
    signalBridge: 'सिग्नल ब्रिज',
    wifi4g: 'वाई-फाई + 4जी',
    cloudSync: 'क्लाउड सिंक',
    devicesConnected: '250+',
    devicesConnectedCount: 'उपकरण जुड़े हैं',
    collarFlow1: 'गति और तापमान महसूस करें',
    collarFlow2: 'लाइव व्यवहार सिग्नल को कंप्रेस करें',
    collarFlow3: 'लोरा पर प्रसारित करें',
    cupFlow1: 'आरएफआईडी द्वारा पशु की पहचान करें',
    cupFlow2: 'सभी चार थनों का नमूना लें',
    cupFlow3: 'रसायन विज्ञान + रियोलॉजी लौटाएं',
    hubFlow1: 'कॉलर और कप पैकेट एकत्र करें',
    hubFlow2: 'बफ़र रीडिंग',
    hubFlow3: 'एक झुंड टाइमलाइन को सिंक करें',
    mcuName: 'ईएसपी-डब्ल्यूआरयूएम-32 (ESP-WROOM-32)',
    mcuRole: 'कोर नियंत्रक',
    collarMcuDetail: 'डीप-स्लीप शेड्यूलिंग, सेंसर पढ़ता है, लोरा पैकेट बनाता है।',
    imuName: 'एमपीयू6050 (MPU6050)',
    imuRole: 'गतिशीलता और जुगाली',
    imuDetail: 'एक्सेलेरोमीटर + जायरोस्कोप जबड़े की लय और सिर की गति को पकड़ता है; >15% की जुगाली की गिरावट संकट का संकेत देती है।',
    tempName: 'डीएस18बी20 (DS18B20)',
    tempRole: 'त्वचा का तापमान',
    tempDetail: 'गर्दन के खिलाफ वॉटरप्रूफ प्रोब बेसल तापमान और प्री-क्लिनिकल बुखार को ट्रैक करता है।',
    radioName: 'एसएक्स1278 लोरा (SX1278 LoRa)',
    radioRole: 'लंबी दूरी का रेडियो',
    radioDetail: 'बिना सिम कार्ड या वाई-फाई के गेटवे पर 3-5 किमी टेलीमेट्री भेजता है।',
    solarName: 'सौर + 18650 सेल',
    solarRole: 'शक्ति',
    collarSolarDetail: '~195 दिन के डार्क रिजर्व के लिए 1W पैनल बैटरी को ट्रिकल-चार्ज करता है।',
    cupMcuDetail: 'अनुक्रमिक 4-तिमाही सैंपलिंग चलाता है और OLED UI को चलाता है।',
    ecPhName: 'ईसी + पीएच प्रोब',
    ecPhRole: 'दूध रसायन',
    ecPhDetail: 'स्तन के ऊतकों के रिसने की आयनिक चालकता वृद्धि और क्षारीय बदलाव (पीएच > 6.8) का पता लगाता है।',
    cmtName: 'मोटर + आईएनए219',
    cmtRole: 'चिपचिपाहट (CMT)',
    cmtDetail: 'एक गियर वाला पैडल गाढ़े जेल के खिलाफ दबाव डालता है; करंट ड्रा दैहिक कोशिका की गिनती को मापता है।',
    irName: 'एमएलएक्स90614 (MLX90614)',
    irRole: 'आईआर थन का तापमान',
    irDetail: 'केवल सतह की गर्मी से स्थानीयकृत सूजन को चिह्नित करता है।',
    rfidName: '134.2 kHz एलएफ आरएफआईडी',
    rfidRole: 'पशु आईडी',
    rfidDetail: 'दूध और कीचड़ के माध्यम से एक सेकंड से भी कम समय में आरएफआईडी टैग पढ़ता है।',
    gatewayName: 'लोरा गेटवे',
    gatewayRole: 'सिग्नल संग्रह',
    gatewayDetail: 'शेड और खेत के किनारे कॉलर और कप से एन्क्रिप्टेड टेलीमेट्री प्राप्त करता है।',
    backhaulName: 'वाई-फाई + 4जी बैकहॉल',
    backhaulRole: 'क्लाउड सिंक',
    backhaulDetail: 'खेत के नेटवर्क की स्थिति बदलने पर भी झुंड की समयरेखा को चालू रखता है।',
    storageName: 'एज बफ़र',
    storageRole: 'ऑफ़लाइन लचीलापन',
    storageDetail: 'रीडिंग को स्थानीय रूप से संग्रहीत करता है और कनेक्टिविटी वापस आने पर उन्हें अग्रेषित करता है।',
    hubPowerName: 'बैटरी बैकअप',
    hubPowerRole: 'हमेशा चालू अपटाइम',
    hubPowerDetail: 'छोटी बिजली रुकावटों के माध्यम से सिग्नल ब्रिज को बनाए रखता है।',
    hubSolarName: 'सौर ऊर्जा से चार्जिंग',
    hubSolarRole: 'अक्षय ऊर्जा',
    hubSolarDetail: 'सेंट्रल हब को चार्ज और निरंतर संचालन के लिए तैयार रखने के लिए सूरज की रोशनी का उपयोग करता है।',
    step1Title: 'कॉलर आरएफआईडी टैग को स्कैन करें',
    step1Detail: 'कप का आरएफआईडी रीडर 500ms से भी कम समय में पशु आईडी और दुद्ध निकालना का इतिहास खींचता है।',
    step2Title: 'प्रत्येक तिमाही का नमूना लें',
    step2Detail: 'ईसी, पीएच और आईआर तापमान को प्रति तिमाही पढ़ा जाता है, ~10 सेकंड प्रत्येक।',
    step3Title: 'CMT जाँच चलाएँ',
    step3Detail: 'एक मोटर चालित पैडल स्पिन अभिकर्मक चिपचिपाहट को मापता है - एससीसी के लिए एक अपरिवर्तनीय प्रॉक्सी।',
    step4Title: 'लोरा पर प्रसारित करें',
    step4Detail: 'कप और कॉलर दोनों शेड गेटवे पर एन्क्रिप्टेड पैकेट भेजते हैं।',
    step5Title: 'फ्यूज और पूर्वानुमान',
    step5Detail: 'क्लाउड एआई रसायन विज्ञान, जुगाली और मौसम को 7-14 दिन के जोखिम स्कोर में मिलाता है।',
    step6Title: 'अलर्ट भेजें',
    step6Detail: 'अलर्ट किसानों और पशु चिकित्सकों को भेजे जाते हैं ताकि सही देखभाल जल्द शुरू हो सके।',
    adminConsole: 'व्यवस्थापक कंसोल',
    vetConsole: 'पशु चिकित्सा अधिकारी कंसोल',
    vetRequests: 'पशु चिकित्सक अनुरोध',

    regionalAnalysis: 'क्षेत्रीय विश्लेषण',
    selectFarmOwner: 'फार्म के मालिक का चयन करें',
    animalName: 'पशु का नाम',
    displayTag: 'डिस्प्ले टैग',
    charRfid: '8-15 अक्षर का RFID',
    remove: 'हटाएं',
    farmLabel: 'फार्म',
    permanentAction: 'स्थायी कार्रवाई',
    removeAnimalConfirm: 'पशु हटाएं',
    removeAccountConfirm: 'खाता हटाएं',
    addAccountOrFarm: 'खाता या फार्म जोड़ें',
    refresh: 'रिफ्रेश करें',
    hubMonitoringByState: 'राज्य द्वारा हब की निगरानी',
    regionalRiskMap: 'क्षेत्रीय जोखिम नक्शा',
    stateLabel: 'राज्य',
    noStatesAvailable: 'कोई राज्य उपलब्ध नहीं है',

    totalFarms: 'कुल फार्म',
    totalAnimals: 'कुल पशु',
    registeredAccounts: 'पंजीकृत खाते',
    highRiskAnimals: 'उच्च जोखिम वाले पशु',
    accountOverview: 'खाता अवलोकन',
    mainAdministrator: 'मुख्य व्यवस्थापक',

  },
  kn: {
    language: 'ಭಾಷೆ',
    dark: 'ಡಾರ್ಕ್',
    light: 'ಲೈಟ್',
    addAnimal: 'ಪ್ರಾಣಿಯನ್ನು ಸೇರಿಸಿ',
    newHerdRecord: 'ಹೊಸ ಹಿಂಡು ದಾಖಲೆ',
    animalType: 'ಪ್ರಾಣಿಯ ಪ್ರಕಾರ',
    name: 'ಹೆಸರು',
    animalId: 'ಪ್ರಾಣಿ ಐಡಿ',
    breed: 'ತಳಿ',
    age: 'ವಯಸ್ಸು (ವರ್ಷಗಳು)',
    ownerId: 'ಮಾಲೀಕರ ಐಡಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    addToHerd: 'ಹಿಂಡಿಗೆ ಸೇರಿಸಿ',
    duplicateId: 'ಈ ಪ್ರಾಣಿ ಐಡಿ ಈಗಾಗಲೇ ಬಳಕೆಯಲ್ಲಿದೆ. ಬೇರೆ ಐಡಿ ಆಯ್ಕೆಮಾಡಿ.',
    highRiskBoard: 'ಹೆಚ್ಚಿನ ಅಪಾಯ ಫಲಕ',
    animalsFlagged: 'ಪ್ರಾಣಿಗಳಿಗೆ ಗುರುತು',
    animal: 'ಪ್ರಾಣಿ',
    species: 'ಪ್ರಭೇದ',
    risk: 'ಅಪಾಯ',
    score: 'ಸ್ಕೋರ್',
    rumination: 'ಮೆಲುಕು Δ',
    view: 'ವೀಕ್ಷಿಸಿ',
    login: 'ಲಾಗ್ ಇನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    uniqueId: 'ಯೂನಿಕ್ ಐಡಿ',
    identifier: 'ಇದರೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    identifierPlaceholder: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    uniqueIdPlaceholder: 'ನಿಮ್ಮ ಯೂನಿಕ್ ಐಡಿ ನಮೂದಿಸಿ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    signIn: 'NANDI ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    createAccount: 'NANDI ಖಾತೆ ರಚಿಸಿ',
    switchToLight: 'ಲೈಟ್ ಮೋಡ್‌ಗೆ ಬದಲಾಯಿಸಿ',
    switchToDark: 'ಡಾರ್ಕ್ ಮೋಡ್‌ಗೆ ಬದಲಾಯಿಸಿ',
    logIn: 'ಲಾಗ್ ಇನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    enterPlatform: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ತೆರೆಯಿರಿ',
    mainPage: 'ಮುಖ್ಯ ಪುಟ',
    herdOverview: 'ಹಿಂಡು ಅವಲೋಕನ',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    predictions: 'ಮುನ್ಸೂಚನೆಗಳು',
    history: 'ಇತಿಹಾಸ',
    animals: 'ಪ್ರಾಣಿಗಳು',
    signupWith: 'ಇದರೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    backHome: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    earlyCare: 'NANDI · ಆರಂಭಿಕ ಆರೈಕೆ ಬುದ್ಧಿಮತ್ತೆ',
    authIntro: 'ಪ್ರತಿ ಹಿಂಡಿನ ಸಂಕೇತವನ್ನು ಗಮನದಲ್ಲಿಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಕಾರ್ಯಸ್ಥಳವನ್ನು ರಚಿಸಿ.',
    allSet: 'ನೀವು ಸಿದ್ಧರಾಗಿದ್ದೀರಿ.',
    workspaceReceived: 'ಕಾರ್ಯಸ್ಥಳ ವಿನಂತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ.',
    prototypeReady: 'ಈ ಮಾದರಿ ಮುಂದಿನ ಹಂತಕ್ಕೆ ಸಿದ್ಧವಾಗಿದೆ. ಹಿಂಡಿನ ದೃಶ್ಯವನ್ನು ನೋಡಲು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ.',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    createWorkspace: 'ನಿಮ್ಮ ಕಾರ್ಯಸ್ಥಳವನ್ನು ರಚಿಸಿ',
    yourName: 'ನಿಮ್ಮ ಹೆಸರು',
    passwordPlaceholder: 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು',
    hidePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆಮಾಡಿ',
    showPassword: 'ಪಾಸ್‌ವರ್ಡ್ ತೋರಿಸಿ',
    rememberMe: 'ನನ್ನನ್ನು ನೆನಪಿನಲ್ಲಿಡಿ',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    terms: 'ಮುಂದುವರಿಯುವ ಮೂಲಕ, ನೀವು NANDI ಕಾರ್ಯಸ್ಥಳದ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೀರಿ.',
    welcomeBackBang: 'ಮತ್ತೆ ಸ್ವಾಗತ!',
    helloPartner: 'ನಮಸ್ಕಾರ ಸಂಗಾತಿ!',
    loginDescription: 'ನಿಮ್ಮ ಹಿಂಡನ್ನು ಸಂಪರ್ಕದಲ್ಲಿಡಲು ವೈಯಕ್ತಿಕ ವಿವರಗಳಿಂದ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    signupDescription: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ಸಂಪರ್ಕಿತ ಹಿಂಡಿನ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ.',
    herdTrends: 'ಎಲ್ಲಾ ಸಂಪರ್ಕಿತ ಸಾಧನಗಳ ಹಿಂಡು-ವ್ಯಾಪಿ ಪ್ರವೃತ್ತಿಗಳು.',
    riskDistribution: 'ಅಪಾಯ ವಿತರಣೆ',
    averageRisk: 'ಪ್ರಭೇದದ ಪ್ರಕಾರ ಸರಾಸರಿ ಅಪಾಯ',
    thi: 'ಶೆಡ್ ತಾಪಮಾನ-ಆರ್ದ್ರತೆ ಸೂಚ್ಯಂಕ (THI)',
    historyDescription: 'ಹಿಂಡಿನ ಘಟನೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳ ಕಾಲಾನುಕ್ರಮದ ದಾಖಲೆ.',
    predictionTitle: 'ಮುನ್ಸೂಚನೆಗಳು ಮತ್ತು ಶಿಫಾರಸುಗಳು',
    predictionDescription: 'ಸಂಯೋಜಿತ ಅಪಾಯ ಸಂಕೇತದಿಂದ ರಚಿಸಲಾದ ವಿವರಿಸಬಹುದಾದ, ಪ್ರಾಣಿ-ನಿರ್ದಿಷ್ಟ ಕ್ರಮಗಳು.',
    viewRecord: 'ಪೂರ್ಣ ಪ್ರಾಣಿ ದಾಖಲೆಯನ್ನು ವೀಕ್ಷಿಸಿ →',
    noRecommendations: 'ಸಕ್ರಿಯ ಶಿಫಾರಸುಗಳಿಲ್ಲ — ಹಿಂಡು ಸುರಕ್ಷಿತವಾಗಿದೆ.',
    speciesLabel: 'ಪ್ರಭೇದ',
    ageLabel: 'ವಯಸ್ಸು',
    lactation: 'ಹಾಲು ನೀಡುವ ಅವಧಿ',
    riskScore: 'ಅಪಾಯ ಸ್ಕೋರ್',
    noAnimals: 'ಈ ಪ್ರಭೇದಕ್ಕೆ ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಾಣಿಗಳು ದಾಖಲಾಗಿಲ್ಲ.',
    cooperative: 'ಕೋಲಾರ ಗ್ರಾಮ / ಹಾಲು ಸಹಕಾರಿ',
    healthConsole: 'ಹಿಂಡು ಆರೋಗ್ಯ ಕನ್ಸೋಲ್',
    gatewayOnline: 'ಗೇಟ್‌ವೇ ಆನ್‌ಲೈನ್ · 99.4% ಅಪ್‌ಟೈಮ್',
    fieldSignal: 'ಕ್ಷೇತ್ರ ಸಂಕೇತ / 24-7',
    knowSooner: 'ಮೊದಲೇ ತಿಳಿಯಿರಿ.',
    careBetter: 'ಉತ್ತಮ ಆರೈಕೆ ಮಾಡಿ.',
    heroDescription: 'NANDI ನಡವಳಿಕೆ ಮತ್ತು ಹಾಲಿನ ರಸಾಯನಶಾಸ್ತ್ರದಲ್ಲಿನ ಸೂಕ್ಷ್ಮ ಬದಲಾವಣೆಗಳನ್ನು ಪ್ರತಿಯೊಂದು ಪ್ರಾಣಿಗೂ ಸ್ಪಷ್ಟ ಆರೈಕೆ ಸಮಯವಾಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ.',
    exploreSystem: 'ವ್ಯವಸ್ಥೆಯನ್ನು ಅನ್ವೇಷಿಸಿ',
    watchDemo: 'YouTube ನಲ್ಲಿ ಡೆಮೋ ನೋಡಿ',
    signalWatch: 'ಸಂಕೇತ ವೀಕ್ಷಣೆ',
    live: 'ಲೈವ್',
    behaviourConfidence: 'ನಡವಳಿಕೆ ವಿಶ್ವಾಸ · ಹಿಂಡು ಸರಾಸರಿ',
    earlyCareWindow: 'ಆರಂಭಿಕ ಆರೈಕೆ ಸಮಯ',
    beforeSymptoms: 'ಲಕ್ಷಣಗಳು ಕಾಣಿಸಿಕೊಳ್ಳುವ ಮೊದಲು',
    connectedView: 'ಒಂದು ಸಂಪರ್ಕಿತ ನೋಟ',
    wholeHerd: 'ಇಡೀ ಹಿಂಡಿಗಾಗಿ',
    todayInHerd: 'ಇಂದು ಹಿಂಡಿನಲ್ಲಿ',
    earlierSignal: 'ಸ್ಪಷ್ಟ ದಿನವು ಮುಂಚಿನ ಸಂಕೇತದಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.',
    liveReadings: 'ಪ್ರತಿ ಸಂಪರ್ಕಿತ ಪ್ರಾಣಿಯ ಲೈವ್ ಓದುವಿಕೆಗಳನ್ನು ಈಗ ಮುಖ್ಯವಾದ ಆರೈಕೆ ನಿರ್ಧಾರಗಳಾಗಿ ಸಂಕ್ಷೇಪಿಸಲಾಗಿದೆ.',
    herdSize: 'ಹಿಂಡಿನ ಗಾತ್ರ',
    acrossSpecies: '3 ಪ್ರಭೇದಗಳಲ್ಲಿ',
    needsVet: 'ಪಶುವೈದ್ಯರ ಗಮನ ಅಗತ್ಯ',
    averageRiskScore: 'ಸರಾಸರಿ ಅಪಾಯ ಸ್ಕೋರ್',
    herdWide: 'ಇಡೀ ಹಿಂಡಿನ',
    gatewayUptime: 'ಗೇಟ್‌ವೇ ಅಪ್‌ಟೈಮ್',
    last30Days: 'ಕಳೆದ 30 ದಿನಗಳು',
    liveHerdReview: 'ಲೈವ್ ಹಿಂಡು ಪರಿಶೀಲನೆ',
    updatedMoments: 'ಇದೀಗ ನವೀಕರಿಸಲಾಗಿದೆ',
    noRiskAnimals: 'ಈಗ ಯಾವುದೇ ಮಧ್ಯಮ ಅಥವಾ ಹೆಚ್ಚಿನ ಅಪಾಯದ ಪ್ರಾಣಿಗಳಿಲ್ಲ.',
    enterAnimalProfile: 'ಈ ಪ್ರಾಣಿಯನ್ನು ನಿಮ್ಮ ಹಿಂಡಿಗೆ ಸೇರಿಸಲು ಪ್ರೊಫೈಲ್ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
    rfidTagLabel: 'RFID / AIN ಟ್ಯಾಗ್ (8-15 ಅಕ್ಷರಗಳು ಮತ್ತು ಅಂಕೆಗಳು)',
    rfidTagHelp: 'ESP32-S3 ರೀಡರ್ ಕಿವಿ ಟ್ಯಾಗ್‌ನಿಂದ ಇದನ್ನೇ ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತದೆ.',
    lactationNumberLabel: 'ಹಾಲುಣಿಸುವ ಸಂಖ್ಯೆ',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ…',
    cowLabel: 'ಹಸು',
    buffaloLabel: 'ಎಮ್ಮೆ',
    shedThiShort: 'ಶೆಡ್ THI',
    runPredictionNow: 'ಈಗ ಮುನ್ಸೂಚನೆ ಚಲಾಯಿಸಿ',
    running: 'ಚಾಲನೆಯಲ್ಲಿದೆ…',
    quarterLevelReadings: 'ಕ್ವಾರ್ಟರ್-ಮಟ್ಟದ ವಾಚನಗಳು',
    noQuarterReadings: 'ಇನ್ನೂ ಕ್ವಾರ್ಟರ್-ಮಟ್ಟದ ವಾಚನಗಳಿಲ್ಲ — ಈ ಪ್ರಾಣಿಗೆ ಮೊದಲ ಸ್ಮಾರ್ಟ್ ಕಪ್ ಟೆಲಿಮೆಟ್ರಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ.',
    recommendedAction: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ',
    findNearbyVet: 'ಹತ್ತಿರದ ಪಶುವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    riskTrend30: '30-ದಿನದ ಅಪಾಯ ಪ್ರವೃತ್ತಿ',
    noRiskHistory: 'ಈ ಪ್ರಾಣಿಗೆ ಇನ್ನೂ ಅಪಾಯದ ಇತಿಹಾಸವಿಲ್ಲ.',
    historyTitle: 'ಇತಿಹಾಸ',
    analyticsTitle: 'ವಿಶ್ಲೇಷಣೆ',
    liveAlertLabel: 'ಲೈವ್ ಎಚ್ಚರಿಕೆ',
    dismissAlert: 'ಎಚ್ಚರಿಕೆ ವಜಾಗೊಳಿಸಿ',
    roleLabel: 'ಪಾತ್ರ',
    emailLabel: 'ಇಮೇಲ್',
    emailPlaceholder: 'you@example.com',
    pleaseWait: 'ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ…',
    demoAccountsNote: 'ಡೆಮೊ ಖಾತೆಗಳು: farmer@nandi.test · vet@nandi.test · admin@nandi.test — ಪಾಸ್‌ವರ್ಡ್: Password123!',
    signInIdentifierLabel: 'ಇಮೇಲ್, ಫೋನ್ ಅಥವಾ ಫಾರ್ಮ್ ಐಡಿ',
    signInIdentifierPlaceholder: 'ಇಮೇಲ್ / ಫೋನ್ / ಫಾರ್ಮ್ ಐಡಿ ನಮೂದಿಸಿ',
    phoneLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    phoneRequiredNote: 'ಅಗತ್ಯವಿದೆ — ತುರ್ತು WhatsApp/SMS ಮಾಸ್ಟೈಟಿಸ್ ಎಚ್ಚರಿಕೆಗಳಿಗಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ.',
    farmNameLabel: 'ಫಾರ್ಮ್ / ಸಹಕಾರಿ ಹೆಸರು (ಐಚ್ಛಿಕ)',
    farmNamePlaceholder: 'ಉದಾ. ಪಟೇಲ್ ಡೈರಿ ಫಾರ್ಮ್',
    farmIdIssued: 'ನಿಮ್ಮ ಫಾರ್ಮ್ ಐಡಿ',
    farmIdExplain: 'ಈ ಫಾರ್ಮ್ ಐಡಿಯನ್ನು ನಿಮ್ಮ ಪ್ರತಿ ಹಬ್, ಕಾಲರ್ ಮತ್ತು ಕಪ್‌ನಲ್ಲಿ ನಮೂದಿಸಿ, ಇದರಿಂದ ಡೇಟಾ ಯಾವಾಗಲೂ ನಿಮ್ಮ ಹಿಂಡಿಗೆ ಮಾತ್ರ ಉಳಿಸಲ್ಪಡುತ್ತದೆ.',
    copyFarmId: 'ನಕಲಿಸಿ',
    copiedFarmId: 'ನಕಲಿಸಲಾಗಿದೆ!',
    logOut: 'ಲಾಗ್ ಔಟ್',
    herdAvgTrend30: 'ಹಿಂಡಿನ ಸರಾಸರಿ ಅಪಾಯ ಸ್ಕೋರ್ (30 ದಿನಗಳು)',
    noHerdTrend: 'ಇನ್ನೂ ಅಪಾಯದ ಇತಿಹಾಸವಿಲ್ಲ — ಟೆಲಿಮೆಟ್ರಿ ಪ್ರಾರಂಭವಾದ ನಂತರ ಪ್ರವೃತ್ತಿ ಕಾಣಿಸುತ್ತದೆ.',
    loadingHerd: 'ನಿಮ್ಮ ಹಿಂಡನ್ನು ಬ್ಯಾಕೆಂಡ್‌ನಿಂದ ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ…',
    checkingSession: 'ನಿಮ್ಮ ಸೆಶನ್ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…',
    exploreSignal: 'ಸಂಕೇತವನ್ನು ಅನ್ವೇಷಿಸಿ', smartCollar: 'ಸ್ಮಾರ್ಟ್ ಕಾಲರ್', smartCollarDescription: 'ಇದು ವರ್ತನೆ, ಜುಗಾಲಿ ಮತ್ತು ಚಲನೆಯನ್ನು ನಿರಂತರವಾಗಿ ಗಮನಿಸುತ್ತದೆ.', smartCup: 'ಡಿಜಿ-ಕಪ್', smartCupDescription: 'ಹಾಲುಹೀರುವ ಸಮಯದಲ್ಲಿ ಪ್ರತಿ ಕ್ವಾರ್ಟರ್ ಅನ್ನು 45 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಪರೀಕ್ಷಿಸುತ್ತದೆ.', nandiHub: 'ಸೆಂಟ್ರಲ್ ಹಬ್', nandiHubDescription: 'ಯಾವಾಗಲೂ ಚಾಲನೆಯಲ್ಲಿರುವ ಗೇಟ್‌ವೇ ಎಲ್ಲಾ ಕಾಲರ್ ಮತ್ತು ಕಪ್ ಸಂಕೇತಗಳನ್ನು ಸಂಗ್ರಹಿಸುತ್ತದೆ.', threeSignals: 'ಮೂರು ಸಂಕೇತಗಳು. ಒಂದು ಶಾಂತ ದಿನ.', threeSignalsDescription: 'ಪ್ರತಿ ಸಂಕೇತಕ್ಕೂ ಸ್ಥಳವಿದೆ: ಪ್ರಾಣಿಯ ಮೇಲೆ, ಹಾಲುಹೀರುವ ಸಮಯದಲ್ಲಿ ಮತ್ತು ಗೇಟ್‌ವೇಯಲ್ಲಿ.', nandiDevices: 'NANDI ಸಾಧನಗಳು', alwaysOnSensing: 'ಯಾವಾಗಲೂ ಚಾಲನೆಯಲ್ಲಿರುವ ಸಂವೇದನೆ', milkingIntelligence: 'ಹಾಲುಹೀರುವ ಬುದ್ಧಿಮತ್ತೆ', farmWideRelay: 'ಫಾರ್ಮ್-ವ್ಯಾಪಿ ರಿಲೇ', workflowTitle: 'ಸ್ತನದಿಂದ ಎಚ್ಚರಿಕೆಯವರೆಗೆ, ಆರು ಹಂತಗಳಲ್ಲಿ',
    optional: 'ಐಚ್ಛಿಕ', alertLanguage: 'ಎಚ್ಚರಿಕೆ ಭಾಷೆ', alertLanguageHelp: 'Twilio ಎಚ್ಚರಿಕೆಗಳು ಈ ಭಾಷೆಯನ್ನು ಬಳಸುತ್ತವೆ.', removeAnimal: 'ಪ್ರಾಣಿಯನ್ನು ತೆಗೆದುಹಾಕಿ', dateAxis: 'ದಿನಾಂಕ', speciesAxis: 'ಪ್ರಭೇದ', riskAxis: 'ಅಪಾಯ ಸ್ಕೋರ್ (%)', weeklyCheckIn: 'ವಾರದ ಪರಿಶೀಲನೆ', weeklyInputTitle: 'ವಾರದ ಹಿಂಡು ಪರಿಶೀಲನೆ', weeklyInputDescription: 'ಪ್ರತಿ ವಾರ ಸಂಖ್ಯಾತ್ಮಕ ಅಥವಾ ಆಯ್ಕೆ ಆಧಾರಿತ ಮಾಹಿತಿಯನ್ನು ದಾಖಲಿಸಿ.', weekStarting: 'ವಾರ ಆರಂಭ', morningMilking: 'ಬೆಳಗಿನ ಹಾಲುಹೀರುವಿಕೆ', eveningMilking: 'ಸಂಜೆಯ ಹಾಲುಹೀರುವಿಕೆ', feedKg: 'ದಿನಕ್ಕೆ ಆಹಾರ (ಕೆಜಿ)', workerHygiene: 'ಕಾರ್ಮಿಕ ಸ್ವಚ್ಛತೆ', good: 'ಉತ್ತಮ', needsAttention: 'ಗಮನ ಅಗತ್ಯ', poor: 'ಕಳಪೆ', antidoteGiven: 'ಯಾವುದೇ ಹಸುವಿಗೆ ಪ್ರತಿವಿಷ ನೀಡಲಾಗಿದೆಯೇ?', antidoteAnimal: 'ಪ್ರತಿವಿಷ ಪ್ರಾಣಿ ಐಡಿ', selectAnimal: 'ಪ್ರಾಣಿ ಆಯ್ಕೆಮಾಡಿ', yes: 'ಹೌದು', no: 'ಇಲ್ಲ', saveWeeklyInput: 'ವಾರದ ಮಾಹಿತಿ ಉಳಿಸಿ', weeklySaved: 'ವಾರದ ಪರಿಶೀಲನೆ ಉಳಿಸಲಾಗಿದೆ.', downloadApk: 'Android ಅಪ್ಲಿಕೇಶನ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', disclaimer: 'ಹಕ್ಕು ನಿರಾಕರಣೆ', contact: 'ಸಂಪರ್ಕ', apkUnavailable: 'Android ಪ್ಯಾಕೇಜ್', footerAbout: 'ಸ್ಮಾರ್ಟ್ ಇಂಡಿಯಾ ಹ್ಯಾಕಥಾನ್ 2026 ಮತ್ತು ಸಮಸ್ಯೆ 26109 ಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.', footerDisclaimer: 'NANDI ಪ್ರಮಾಣಿತ ಪಶುವೈದ್ಯಕೀಯ ಸಾಧನವಲ್ಲ, ಇದು ಹ್ಯಾಕಥಾನ್ ಮಾದರಿ ಮತ್ತು ನಿರ್ಧಾರ ಸಹಾಯ ಸಾಧನವಾಗಿದೆ.',

    mpu6050: 'MPU6050',
    motility: 'ಚಲನಶೀಲತೆ',
    loraRadio: 'LoRa ರೇಡಿಯೋ',
    loraRange: '3-5 ಕಿಮೀ ಶ್ರೇಣಿ',
    solarCell: 'ಸೌರ ಕೋಶ',
    solarReserve: '195-ದಿನಗಳ ಮೀಸಲು',
    ecPh: 'EC + pH',
    chemistry: 'ರಸಾಯನಶಾಸ್ತ್ರ',
    irProbe: 'IR ಪ್ರೋಬ್',
    temperature: 'ತಾಪಮಾನ',
    rfid: 'RFID',
    lora: 'LoRa',
    signalBridge: 'ಸಿಗ್ನಲ್ ಸೇತುವೆ',
    wifi4g: 'Wi-Fi + 4G',
    cloudSync: 'ಕ್ಲೌಡ್ ಸಿಂಕ್',
    devicesConnected: '250+',
    devicesConnectedCount: 'ಸಾಧನಗಳು ಸಂಪರ್ಕಗೊಂಡಿವೆ',
    collarFlow1: 'ಚಲನೆ ಮತ್ತು ತಾಪಮಾನವನ್ನು ಗ್ರಹಿಸಿ',
    collarFlow2: 'ಲೈವ್ ವರ್ತನೆಯ ಸಂಕೇತವನ್ನು ಸಂಕುಚಿತಗೊಳಿಸಿ',
    collarFlow3: 'LoRa ಮೂಲಕ ಪ್ರಸಾರ ಮಾಡಿ',
    cupFlow1: 'RFID ಮೂಲಕ ಪ್ರಾಣಿಯನ್ನು ಗುರುತಿಸಿ',
    cupFlow2: 'ನಾಲ್ಕೂ ಭಾಗಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ',
    cupFlow3: 'ರಸಾಯನಶಾಸ್ತ್ರ + ರಿಯಾಲಜಿ ಹಿಂತಿರುಗಿ',
    hubFlow1: 'ಕಾಲರ್ ಮತ್ತು ಕಪ್ ಪ್ಯಾಕೆಟ್‌ಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ',
    hubFlow2: 'ಬಫರ್ ವಾಚನಗಳು',
    hubFlow3: 'ಒಂದು ಹಿಂಡಿನ ಟೈಮ್‌ಲೈನ್ ಸಿಂಕ್ ಮಾಡಿ',
    mcuName: 'ESP-WROOM-32',
    mcuRole: 'ಕೋರ್ ನಿಯಂತ್ರಕ',
    collarMcuDetail: 'ಡೀಪ್-ಸ್ಲೀಪ್ ಶೆಡ್ಯೂಲಿಂಗ್, ಸೆನ್ಸರ್‌ಗಳನ್ನು ಓದುತ್ತದೆ, LoRa ಪ್ಯಾಕೆಟ್‌ಗಳನ್ನು ರಚಿಸುತ್ತದೆ.',
    imuName: 'MPU6050',
    imuRole: 'ಚಲನಶೀಲತೆ ಮತ್ತು ಜುಗಾಲಿ',
    imuDetail: 'ಆಕ್ಸಿಲರೊಮೀಟರ್ + ಗೈರೊಸ್ಕೋಪ್ ದವಡೆಯ ಲಯ ಮತ್ತು ತಲೆಯ ಚಲನೆಯನ್ನು ಹಿಡಿಯುತ್ತದೆ; >15% ಜುಗಾಲಿ ಕುಸಿತವು ಅಪಾಯವನ್ನು ಸೂಚಿಸುತ್ತದೆ.',
    tempName: 'DS18B20',
    tempRole: 'ಚರ್ಮದ ತಾಪಮಾನ',
    tempDetail: 'ಕತ್ತಿನ ಮೇಲಿನ ವಾಟರ್‌ಪ್ರೂಫ್ ಪ್ರೋಬ್ ಮೂಲ ತಾಪಮಾನ ಮತ್ತು ಕ್ಲಿನಿಕಲ್ ಪೂರ್ವ ಜ್ವರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತದೆ.',
    radioName: 'SX1278 LoRa',
    radioRole: 'ದೂರಗಾಮಿ ರೇಡಿಯೋ',
    radioDetail: 'ಸಿಮ್ ಕಾರ್ಡ್ ಅಥವಾ ವೈ-ಫೈ ಇಲ್ಲದೆ 3-5 ಕಿಮೀ ದೂರದ ಗೇಟ್‌ವೇಗೆ ಟೆಲಿಮೆಟ್ರಿಯನ್ನು ಕಳುಹಿಸುತ್ತದೆ.',
    solarName: 'ಸೌರ + 18650 ಸೆಲ್',
    solarRole: 'ಶಕ್ತಿ',
    collarSolarDetail: '~195 ದಿನಗಳ ಡಾರ್ಕ್ ರಿಸರ್ವ್‌ಗಾಗಿ 1W ಪ್ಯಾನಲ್ ಬ್ಯಾಟರಿಯನ್ನು ಟ್ರಿಕಲ್-ಚಾರ್ಜ್ ಮಾಡುತ್ತದೆ.',
    cupMcuDetail: 'ಅನುಕ್ರಮ 4-ಕ್ವಾರ್ಟರ್ ಸ್ಯಾಂಪ್ಲಿಂಗ್ ಅನ್ನು ರನ್ ಮಾಡುತ್ತದೆ ಮತ್ತು OLED UI ಅನ್ನು ಚಾಲನೆ ಮಾಡುತ್ತದೆ.',
    ecPhName: 'EC + pH ಪ್ರೋಬ್‌ಗಳು',
    ecPhRole: 'ಹಾಲಿನ ರಸಾಯನಶಾಸ್ತ್ರ',
    ecPhDetail: 'ಸೋರುವ ಸ್ತನ ಅಂಗಾಂಶದ ಅಯಾನಿಕ್ ವಾಹಕತೆಯ ಏರಿಕೆ ಮತ್ತು ಕ್ಷಾರೀಯ ಬದಲಾವಣೆಯನ್ನು (pH > 6.8) ಪತ್ತೆ ಮಾಡುತ್ತದೆ.',
    cmtName: 'ಮೋಟರ್ + INA219',
    cmtRole: 'ಸ್ನಿಗ್ಧತೆ (CMT)',
    cmtDetail: 'ಗೇರ್ಡ್ ಪ್ಯಾಡಲ್ ದಪ್ಪಗಾದ ಜೆಲ್ ವಿರುದ್ಧ ಒತ್ತುತ್ತದೆ; ಕರೆಂಟ್ ಡ್ರಾ ದೈಹಿಕ ಜೀವಕೋಶದ ಎಣಿಕೆಯನ್ನು ಅಳೆಯುತ್ತದೆ.',
    irName: 'MLX90614',
    irRole: 'IR ತೊಟ್ಟಿನ ತಾಪಮಾನ',
    irDetail: 'ಮೇಲ್ಮೈ ಶಾಖದಿಂದಲೇ ಸ್ಥಳೀಯ ಊತವನ್ನು ಗುರುತಿಸುತ್ತದೆ.',
    rfidName: '134.2 kHz LF RFID',
    rfidRole: 'ಪ್ರಾಣಿ ID',
    rfidDetail: 'ಹಾಲು ಮತ್ತು ಮಣ್ಣಿನ ಮೂಲಕ ಒಂದು ಸೆಕೆಂಡಿಗಿಂತ ಕಡಿಮೆ ಅವಧಿಯಲ್ಲಿ RFID ಟ್ಯಾಗ್ ಅನ್ನು ಓದುತ್ತದೆ.',
    gatewayName: 'LoRa ಗೇಟ್‌ವೇ',
    gatewayRole: 'ಸಿಗ್ನಲ್ ಸಂಗ್ರಹಣೆ',
    gatewayDetail: 'ಶೆಡ್ ಮತ್ತು ಹೊಲದ ಅಂಚಿನಾದ್ಯಂತ ಕಾಲರ್‌ಗಳು ಮತ್ತು ಕಪ್‌ಗಳಿಂದ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾದ ಟೆಲಿಮೆಟ್ರಿಯನ್ನು ಸ್ವೀಕರಿಸುತ್ತದೆ.',
    backhaulName: 'Wi-Fi + 4G ಬ್ಯಾಕ್‌ಹಾಲ್',
    backhaulRole: 'ಕ್ಲೌಡ್ ಸಿಂಕ್',
    backhaulDetail: 'ಫಾರ್ಮ್ ನೆಟ್‌ವರ್ಕ್ ಸ್ಥಿತಿ ಬದಲಾದಾಗಲೂ ಹಿಂಡಿನ ಟೈಮ್‌ಲೈನ್ ಅನ್ನು ಪ್ರಸ್ತುತವಾಗಿರಿಸುತ್ತದೆ.',
    storageName: 'ಎಡ್ಜ್ ಬಫರ್',
    storageRole: 'ಆಫ್‌ಲೈನ್ ಸ್ಥಿತಿಸ್ಥಾಪಕತ್ವ',
    storageDetail: 'ರೀಡಿಂಗ್‌ಗಳನ್ನು ಸ್ಥಳೀಯವಾಗಿ ಸಂಗ್ರಹಿಸುತ್ತದೆ ಮತ್ತು ಸಂಪರ್ಕವು ಹಿಂತಿರುಗಿದಾಗ ಅವುಗಳನ್ನು ರವಾನಿಸುತ್ತದೆ.',
    hubPowerName: 'ಬ್ಯಾಟರಿ ಬ್ಯಾಕಪ್',
    hubPowerRole: 'ಯಾವಾಗಲೂ ಆನ್ ಅಪ್‌ಟೈಮ್',
    hubPowerDetail: 'ಸಣ್ಣ ವಿದ್ಯುತ್ ಅಡಚಣೆಗಳ ಮೂಲಕ ಸಿಗ್ನಲ್ ಸೇತುವೆಯನ್ನು ನಿರ್ವಹಿಸುತ್ತದೆ.',
    hubSolarName: 'ಸೌರಶಕ್ತಿ ಚಾರ್ಜಿಂಗ್',
    hubSolarRole: 'ನವೀಕರಿಸಬಹುದಾದ ಶಕ್ತಿ',
    hubSolarDetail: 'ಸೆಂಟ್ರಲ್ ಹಬ್ ಅನ್ನು ಚಾರ್ಜ್ ಮಾಡಲು ಮತ್ತು ನಿರಂತರ ಕಾರ್ಯಾಚರಣೆಗೆ ಸಿದ್ಧವಾಗಿರಿಸಲು ಸೂರ್ಯನ ಬೆಳಕನ್ನು ಬಳಸುತ್ತದೆ.',
    step1Title: 'ಕಾಲರ್ RFID ಟ್ಯಾಗ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    step1Detail: 'ಕಪ್‌ನ RFID ರೀಡರ್ 500ms ಗಿಂತ ಕಡಿಮೆ ಅವಧಿಯಲ್ಲಿ ಪ್ರಾಣಿ ID ಮತ್ತು ಹಾಲುಕರೆಯುವ ಇತಿಹಾಸವನ್ನು ಎಳೆಯುತ್ತದೆ.',
    step2Title: 'ಪ್ರತಿಯೊಂದು ಭಾಗವನ್ನು ಪರೀಕ್ಷಿಸಿ',
    step2Detail: 'EC, pH ಮತ್ತು IR ತಾಪಮಾನವನ್ನು ಪ್ರತಿ ಕ್ವಾರ್ಟರ್‌ಗೆ ಓದಲಾಗುತ್ತದೆ, ಪ್ರತಿಯೊಂದಕ್ಕೂ ~10 ಸೆಕೆಂಡುಗಳು.',
    step3Title: 'CMT ಪರಿಶೀಲನೆ ರನ್ ಮಾಡಿ',
    step3Detail: 'ಮೋಟಾರೀಕೃತ ಪ್ಯಾಡಲ್ ಸ್ಪಿನ್ ಕಾರಕದ ಸ್ನಿಗ್ಧತೆಯನ್ನು ಅಳೆಯುತ್ತದೆ - SCC ಗಾಗಿ ವಂಚಿಸಲಾಗದ ಪ್ರಾಕ್ಸಿ.',
    step4Title: 'LoRa ಮೂಲಕ ಪ್ರಸಾರ ಮಾಡಿ',
    step4Detail: 'ಕಪ್ ಮತ್ತು ಕಾಲರ್ ಎರಡೂ ಶೆಡ್ ಗೇಟ್‌ವೇಗೆ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾದ ಪ್ಯಾಕೆಟ್‌ಗಳನ್ನು ಕಳುಹಿಸುತ್ತವೆ.',
    step5Title: 'ಫ್ಯೂಸ್ ಮತ್ತು ಮುನ್ಸೂಚನೆ',
    step5Detail: 'ಕ್ಲೌಡ್ AI ರಸಾಯನಶಾಸ್ತ್ರ, ಜುಗಾಲಿ ಮತ್ತು ಹವಾಮಾನವನ್ನು 7-14 ದಿನಗಳ ಅಪಾಯದ ಸ್ಕೋರ್‌ಗೆ ಸಂಯೋಜಿಸುತ್ತದೆ.',
    step6Title: 'ಎಚ್ಚರಿಕೆಗಳನ್ನು ಕಳುಹಿಸಿ',
    step6Detail: 'ರೈತರು ಮತ್ತು ಪಶುವೈದ್ಯರಿಗೆ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಕಳುಹಿಸಲಾಗುತ್ತದೆ, ಇದರಿಂದ ಸರಿಯಾದ ಆರೈಕೆ ಶೀಘ್ರವಾಗಿ ಪ್ರಾರಂಭವಾಗಬಹುದು.',
    adminConsole: 'ಆಡಳಿತಗಾರರ ಕನ್ಸೋಲ್',
    vetConsole: 'ಪಶುವೈದ್ಯಕೀಯ ಅಧಿಕಾರಿ ಕನ್ಸೋಲ್',
    vetRequests: 'ಪಶುವೈದ್ಯರ ವಿನಂತಿಗಳು',

    regionalAnalysis: 'ಪ್ರಾದೇಶಿಕ ವಿಶ್ಲೇಷಣೆ',
    selectFarmOwner: 'ಫಾರ್ಮ್ ಮಾಲೀಕರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    animalName: 'ಪ್ರಾಣಿಯ ಹೆಸರು',
    displayTag: 'ಡಿಸ್ಪ್ಲೇ ಟ್ಯಾಗ್',
    charRfid: '8-15 ಅಕ್ಷರಗಳ RFID',
    remove: 'ತೆಗೆದುಹಾಕಿ',
    farmLabel: 'ಫಾರ್ಮ್',
    permanentAction: 'ಶಾಶ್ವತ ಕ್ರಮ',
    removeAnimalConfirm: 'ಪ್ರಾಣಿಯನ್ನು ತೆಗೆದುಹಾಕಿ',
    removeAccountConfirm: 'ಖಾತೆಯನ್ನು ತೆಗೆದುಹಾಕಿ',
    addAccountOrFarm: 'ಖಾತೆ ಅಥವಾ ಫಾರ್ಮ್ ಸೇರಿಸಿ',
    refresh: 'ರಿಫ್ರೆಶ್ ಮಾಡಿ',
    hubMonitoringByState: 'ರಾಜ್ಯವಾರು ಹಬ್ ಮೇಲ್ವಿಚಾರಣೆ',
    regionalRiskMap: 'ಪ್ರಾದೇಶಿಕ ಅಪಾಯದ ನಕ್ಷೆ',
    stateLabel: 'ರಾಜ್ಯ',
    noStatesAvailable: 'ಯಾವುದೇ ರಾಜ್ಯಗಳು ಲಭ್ಯವಿಲ್ಲ',

    totalFarms: 'ಒಟ್ಟು ಫಾರ್ಮ್‌ಗಳು',
    totalAnimals: 'ಒಟ್ಟು ಪ್ರಾಣಿಗಳು',
    registeredAccounts: 'ನೋಂದಾಯಿತ ಖಾತೆಗಳು',
    highRiskAnimals: 'ಹೆಚ್ಚಿನ ಅಪಾಯದ ಪ್ರಾಣಿಗಳು',
    accountOverview: 'ಖಾತೆ ಅವಲೋಕನ',
    mainAdministrator: 'ಮುಖ್ಯ ಆಡಳಿತಗಾರ',

  },
};

function getInitialLanguage() {
  try {
    const savedLanguage = window.localStorage.getItem(STORAGE_KEY);
    return savedLanguage && LANGUAGES[savedLanguage] ? savedLanguage : 'en';
  } catch {
    return 'en';
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    document.documentElement.lang = language;
    try {
      window.localStorage.setItem(STORAGE_KEY, language);
    } catch {
    }
  }, [language]);

  function t(key) {
    return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
